version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ML_SERVICE_URL=http://ml_service:8001/predict
    depends_on:
      - ml_service

  ml_service:
    build: ./ml_service
    ports:
      - "8001:8001"
    volumes:
      - ./ml_service/model.pkl:/app/model.pkl
